### ISSUE TITLE
Problem Set 1 Checklist

### ISSUE THREAD

**Issue by PrestonMui** [PrestonMui/244-psets#1]
This is the checklist of things to do for problem set 1.
- [x] Identification I (OLS) -- 9152d31e96938cce0b0823e6bcb5110f23533b5e
- [x] Identification II (Structural Labor Supply Model) --  78d688ce2aff55d13e31403c0dc5c84e71ff603d
- [x] Identification III (Mixture of Normals) -- 808e82db4cec63e93778744db30eae3b6264b119
- [x] Quantile Treatment Effects
  - [x] Part a -- 2a311b918f63af1ad3180d9ec923ff2c44367fcb
  - [x] Part b -- ffc3215ccc0abe14300a36c957f44982e563c72a
  - [x] Part c -- 5c39a3028f7b4eeebc1b6e156858f769c232f532
  - [x] Part d -- 5c39a3028f7b4eeebc1b6e156858f769c232f532
- [x] Iterated Projections -- e0e465619ab9e33cb20a5fed568fe90d83bbfd40
- [x] FWL theorem --  450a7cabf0eb5f795a54a1900a86605a47827947
- [x] Weighted average derivative properties
  - [x] Part a -- 6de14925138e4e162464dac99243c0aeeddf5cc9
  - [x] Part b -- ab5062a09f1975682543fb5d874a687f3cbec0cb
  - [x] Part c
  - [x] Part d

**Comment by PrestonMui** [comment]
Added answer for q2, but someone should look over it. See commit 78d688ce2aff55d13e31403c0dc5c84e71ff603d. In particular i'm not sure how to formally show identification, although I'm not sure if we have to.

**Comment by PrestonMui** [comment]
Congratulations everyone.
